name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ENV_NAME: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Записать секрет в файл
        run: echo "${{ secrets.DB_NAME }}" > temp_file.txt
      - name: Прочитать файл
        run: cat temp_file.txt
